### ISSUE TITLE
Fix ImportError for wx pubsub Publisher class with wx versions >=  3.0

### ISSUE THREAD

**Issue by tswilliams** [ipbus/ipbus-software#125]
Before version 3 of wxPython (e.g. in v2.8.x that's present on SLC6 & CentOS7), it used version 1 of the `pubsub` API, meaning that the `Publisher` class was imported as follows:
```
from wx.lib.pubsub import Publisher
```
From version 3 of wxPython, it uses version 3 of the `pubsub` API, and so the import statement for the same class becomes:
```
from wx.lib.pubsub import pub as Publisher
```

The uHAL GUI currently gives the following error with v3.0 of `wxPython`:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/uhal/gui/test/test_uhal_gui.py", line 3, in <module>
    from uhal.gui.guiloader import test
  File "/usr/local/lib/python2.7/dist-packages/uhal/gui/guiloader.py", line 4, in <module>
    from uhal.gui.guis import defaultgui
  File "/usr/local/lib/python2.7/dist-packages/uhal/gui/guis/defaultgui.py", line 4, in <module>
    from wx.lib.pubsub import Publisher
ImportError: cannot import name Publisher
```
It should be updated to so that there's no import error both with wxPython 2.8 and with v3.0.

**Comment by tswilliams** [comment]
Fixed in pull request #126. Closing.
