### ISSUE TITLE
Missing dependencies in pycohal

### ISSUE THREAD

**Issue by tswilliams** [ipbus/ipbus-software#26]
CACTUS TRAC ticket 2209, from Jeroen Hegeman ...

Dear cacti,

It appears that the uhal/pycohal python binding RPM missing most of its dependencies. The RPM contains some dependencies (probably inserted by setuptools or so):

```
$ rpm -q --requires cactuscore-uhal-pycohal

python(abi) = 2.7
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PartialHardlinkSets) <= 4.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
```

But nevertheless:

```
$ python
Python 2.7.5 (default, Nov  6 2016, 00:28:07)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import uhal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/uhal/__init__.py", line 3, in <module>
    from _core import *
ImportError: libcactus_extern_pugixml.so: cannot open shared object file: No such file or directory
```

The above will happen for lots of libraries, since uhal actually has lots of dependencies on things like pugixml and BOOST:

```
$ ldd /usr/lib/python2.7/site-packages/uhal/_core.so
ldd: warning: you do not have execution permission for `/usr/lib/python2.7/site-packages/uhal/_core.so'
        linux-vdso.so.1 =>  (0x00007ffd3135e000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007efd97c02000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007efd979fe000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007efd977fa000)
        libpython2.7.so.1.0 => /lib64/libpython2.7.so.1.0 (0x00007efd9742f000)
        libboost_filesystem.so.1.53.0 => /lib64/libboost_filesystem.so.1.53.0 (0x00007efd97218000)
        libboost_python.so.1.53.0 => /lib64/libboost_python.so.1.53.0 (0x00007efd96fcc000)
        libboost_regex.so.1.53.0 => /lib64/libboost_regex.so.1.53.0 (0x00007efd96cc9000)
        libboost_system.so.1.53.0 => /lib64/libboost_system.so.1.53.0 (0x00007efd96ac5000)
        libboost_thread-mt.so.1.53.0 => /lib64/libboost_thread-mt.so.1.53.0 (0x00007efd968ad000)
        libboost_system-mt.so.1.53.0 => /lib64/libboost_system-mt.so.1.53.0 (0x00007efd966a9000)
        libcactus_extern_pugixml.so => not found
        libcactus_uhal_grammars.so => not found
        libcactus_uhal_log.so => not found
        libcactus_uhal_uhal.so => not found
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007efd9639e000)
        libm.so.6 => /lib64/libm.so.6 (0x00007efd9609c000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007efd95e86000)
        libc.so.6 => /lib64/libc.so.6 (0x00007efd95ac4000)
        /lib64/ld-linux-x86-64.so.2 (0x00007efd98262000)
        libicuuc.so.50 => /lib64/libicuuc.so.50 (0x00007efd9574b000)
        libicui18n.so.50 => /lib64/libicui18n.so.50 (0x00007efd9534b000)
        libicudata.so.50 => /lib64/libicudata.so.50 (0x00007efd93d77000)
        librt.so.1 => /lib64/librt.so.1 (0x00007efd93b6f000)
```

NOTE: According to the RPM, pycohal does not even require uhal.

In a lab setup this is not a big deal, since it is easily fixed, but in a puppet-driven environment like P5 puppet relies on yum to resolve the dependencies and ensure that everything is installed. We recently ran into an issue when we needed uhal on a machine at P5, and later discovered that in order for uhal to work in python, one needs to install boost-python as well. It would have been nice if puppet would have been able to just take care of that for us.

Since the dependencies for cactuscore-uhal-uhal seem to be in order, I suspect one would just need to add cactuscore-uhal-uhal and boost-python to the list of dependencies for cactuscore-uhal-pycohal.

Best regards,
Jeroen

**Comment by tswilliams** [comment]
My response (copied from CACTUS TRAC) ...

 Hi,

 Sorry for this oversight, it will be fixed ASAP.

 Normally the dependencies between C++ libraries are automatically resolved
 for RPMs, but it appears not to be the case for the C++ library containing
 the Python bindings.

 Notes for implementation of fix:
  * The `Requires` line in the specfile that's generated by Python
 `distutils` can be set either through:
    * `uhal/pycohal/Makefile`: Add  the `--requires` option in the `python
 setup.py bdist_rpm`
    * `uhal/pycohal/setup.cfg`: Add `[bdist_rpm]` section and `requires =
 blah` line
  * boost is provided by RPMs of different names on SLC6 and CC7, so at
 least for that dependency, we should specify the boost library name rather
 than RPM names to have an OS-independent solution

 Cheers,
 Tom

**Comment by tswilliams** [comment]
All done; fix manually checked on both SLC6 & CentOS7. Closing.
