### ISSUE TITLE
Cannot import uhal in python3 on alma9 machine

### ISSUE THREAD

**Issue by chevillotn** [ipbus/ipbus-software#308]
I have installed v2.8.12 following the documentation.
Whe i try to import uhal i get an issue with missing uhal_tests library:
```
[root@pc-emf-fw-04 ~]# python
Python 3.9.18 (main, Sep  7 2023, 00:00:00) 
[GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import uhal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/uhal/__init__.py", line 11, in <module>
    exec('raise type(e)(message.format(e.msg)).with_traceback(sys.exc_info()[2]) from None')
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/uhal/__init__.py", line 5, in <module>
    from ._core import *
ImportError: Failed to load uHAL bindings.
Details: "libcactus_uhal_tests.so.2.8: cannot open shared object file: No such file or directory"
>>> 
```

**Comment by tswilliams** [comment]
By default the software will be installed under `/opt/cactus`; have you added `/opt/cactus/lib` to `$LD_LIBRARY_PATH`
